### ISSUE TITLE
Add flags for sliencing warning and for treating warnings as error

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#100]
Users would want to ignore known warnings when writing scripts with `kompose`. Users would also want to get errors when they try to remove all unsupported fields.

**Comment by surajssd** [comment]
I would like to work on this! :)

**Comment by surajssd** [comment]
We can have a global flag `-w` to suppress all the warnings, but I am not clear of the second thing of "treating warnings as error"?

**Comment by janetkuo** [comment]
"Treating warnings as errors" means that "I expect myself to fix my config so that I won't see any warnings; but in case I missed anything, please give me error on those warnings".
