### ISSUE TITLE
Improve usage

### ISSUE THREAD

**Issue by runseb** [skippbox/kompose#11]
Might be a codegangsta issue but the usage is a bit messed up:

    $ kompose k8s ps -h
    Usage: kompose ps [OPTIONS]

    Get active data in the kubernetes cluster

    Options:
       --services, -s	Get active services
       --rc, -r		Get active replication controller
   
Usage should list `kompose k8s ps`
That issue is valid for all subcommands.

Interestingly `kompose k8s` returns the usage for convert alone and not the `kompose k8s help`

**Comment by ngtuna** [comment]
Yes. It also doesn't list subcommands, even show details of the first of them.

`$ kompose k8s -h
Usage: kompose convert [OPTIONS]

Convert docker-compose.yml to Kubernetes object and submit

Options:
   --file, -f "docker-compose.yml"	Specify an alternate compose file (default: docker-compose.yml) [$COMPOSE_FILE]
   --deployment, -d			Generate a deployment resource file
   --chart, -c				Create a chart deployment
   --yaml, -y				Generate a deployment resource file in yaml format  
`

**Comment by janetkuo** [comment]
I have this:
```
$ kompose k8s ps --rc 
Name           Containers     Images                        Replicas  Selectors           
redis          redis          redis:3.0                     3         service=redis

$ kompose k8s ps --svc 
Name                Cluster IP          Ports               Selectors           
redis               10.0.0.83           TCP(6379)           service=redis
```

and I'd expect to see all of them or at least error message without specifying options:
```
$ kompose k8s ps
(returns me nothing)
```

**Comment by ngtuna** [comment]
This issue was solved on [kompose2](https://github.com/skippbox/kompose2)
