### ISSUE TITLE
Create a pod of containers sharing volume

### ISSUE THREAD

**Issue by surajssd** [skippbox/kompose#116]
Right now the way we do conversion is more of one to one mapping. But when two services/containers share volume in docker-compose file we need to put those two containers in a single pod and make them share volume on kubernetes as well.

for e.g.: the following two services should be wound up into a single pod, by which I mean we will only create one deployment, which has one pod and both of those containers, and single service on top of them, if ports provided:

```bash
version: '2'

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
  
  foosvc:
    image: foosvcimage
    volumes:
      - data:/var/lib/my/mount/point

volumes:
  data:
    external: true
```

**Comment by ngtuna** [comment]
That would be great if you can take it. I filed this issue before but have never tried. https://github.com/skippbox/kompose/issues/14

**Comment by surajssd** [comment]
@ngtuna oops sorry for the duplicate will close this, will work on #14 !
