### ISSUE TITLE
Should we use libcompose project.Context{} instead of docker.Context{}?

### ISSUE THREAD

**Issue by weitenghuang** [skippbox/kompose#134]
I may miss something, but I don't understand why we will need to use `&docker.Context{}` when we load compose file in [loader pkg](https://github.com/skippbox/kompose/blob/master/pkg/loader/compose/compose.go#L95)
Isn't [`project.Context{}`](https://github.com/docker/libcompose/blob/master/project/context.go#L21) sufficient? The difference are:
```go
	ClientFactory client.Factory
	ConfigDir     string
	ConfigFile    *configfile.ConfigFile
	AuthLookup    auth.Lookup
```

**Comment by surajssd** [comment]
I think we had discussion on similar lines at https://github.com/skippbox/kompose/pull/67#issuecomment-235262742 and https://github.com/skippbox/kompose/pull/67#issuecomment-235654824 please correct me if I got you all wrong?

**Comment by weitenghuang** [comment]
I propose we use `project.Context` for the same reason you referred in [#67 (comment)](https://github.com/skippbox/kompose/pull/67#issuecomment-235654824). We don't need to use libcompose's `docker` pkg context, if kompose is not meant to build a docker client.
Both support EnvironmentLookup. 
Furthermore, I will help to resolve libcompose [#372](https://github.com/docker/libcompose/issues/372), so we don't need to copy the code here as well.

**Comment by ngtuna** [comment]
+1 @weitenghuang. I made a PR for that. Once your PR solving https://github.com/docker/libcompose/issues/372 get in, we can remove the copied code.
