### ISSUE TITLE
[PROPOSAL] Use -f as a global flag

### ISSUE THREAD

**Issue by runseb** [skippbox/kompose#138]
While testing kompose with the guestbook app (now in the examples folder). I realized that docker-compose uses the -f as a global flag and we use it as an optional flag of the subcommand.

I think we should try to mimic docker-compose as much as we can. To that extent, could we use the  -f as a global flag so that we can do this:

```
kompose -f ./examples/docker-guestbook.yml up
```

Instead of the current behavior

```
kompose up -f ./examples/docker-guestbook.yml
```

**Comment by ngtuna** [comment]
That would be very easy to do
