### ISSUE TITLE
Generate ImageStream for every image in DeploymentConfig

### ISSUE THREAD

**Issue by kadel** [skippbox/kompose#145]
We should generate ImageStream for every image that is used in DeploymentConfig, and use that ImageStream in DC.

**Comment by surajssd** [comment]
@kadel do what is the approach you are following for doing this?

**Comment by kadel** [comment]
it is better practice to use ImageStreams in Openshift. If you are using remote registries with DC you are missing some features, for example automatically triggering new deployments when image changes for this you need ImageStream
