### ISSUE TITLE
Persistent Volumes

### ISSUE THREAD

**Issue by kadel** [skippbox/kompose#150]
We should start thinking about proper volume implementation.

Kompose should create PersistentVolumeClaims and use those for pod volumes, instead of using EmptyDir.

Real persistent volumes might also solve `volumes_from` problem (#131)

**Comment by surajssd** [comment]
Since it was decided that for docker-compose volumes we create k8s PVCs, I am taking this up, so that I can continue the pending work of: https://github.com/skippbox/kompose/issues/14 and https://github.com/skippbox/kompose/pull/131
