### ISSUE TITLE
--file for all kinds of input

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kompose#153]
Playing with Kompose, I see it would be great to use `--file` flag for all kinds of input format such as `bundle` or `compose` like this. We can implement a format detection prior to loading the file into corresponding package.

```console
$ kompose --file docker-compose.yml convert
$ kompose --file docker-bundle.dsb convert
```

**Comment by runseb** [comment]
that's an interesting idea, even though I am bit weary of too much magic to detect file format...

**Comment by ngtuna** [comment]
temporarily close as `--file` and `--bundle` are now global flags.
