### ISSUE TITLE
Support for "9995:9995/tcp"

### ISSUE THREAD

**Issue by SerCeMan** [skippbox/kompose#158]
WARN[0000] Unsupported key expose - ignoring            
WARN[0000] Unsupported key hostname - ignoring          
FATA[0000] "pinpoint-collector" failed to load ports from compose file: invalid container port "9995:9995/tcp"

**Comment by kadel** [comment]
Than you for reporting this. 

It looks like there is a bug in how Kompose parses ports.
It is not expecting that it could be in 'host:container:proto" format.
https://github.com/skippbox/kompose/blob/0c33e7e96517dd85fb96d8ab87fa42ec827bb6cb/pkg/loader/compose/compose.go#L59
