### ISSUE TITLE
kompose up always deploys to default namespace

### ISSUE THREAD

**Issue by kadel** [skippbox/kompose#162]
I have created new namespase and set it as default namespace for `kubectl`.
When I do `kubectl create ...` it creates object in that namespace.

But when I do `kompose up` it still deploys to `default` namespace.

**Comment by ngtuna** [comment]
:+1: Exactly that's not a bug but enhancement :-) Actually for kompose up I'm fixing the default namespace. Let me take this one by investigating the default namespace config from kubectl.

**Comment by kadel** [comment]
I've started to investigating that, as this blocks me from implementing `kompose up` for openshift :-(

**Comment by ngtuna** [comment]
Ah that's okay. So I make a handover to you.
