### ISSUE TITLE
kompose --version - print out dev tag 

### ISSUE THREAD

**Issue by dustymabe** [skippbox/kompose#170]
right now if you run `kompose --version` it will print out:
```
$ ../kompose --version
kompose version 0.1.0 (fa46376)
```
which is a bit misleading because tag `0.1.0` does not correlate to `fa46376` but rather to `8227684`. Could we have kompose print out a 'dev' tag or something when on a commit that doesn't have an associated tag?

**Comment by sebgoa** [comment]
@cab105 that's an easy one for you to get back to work on kompose :)

**Comment by ngtuna** [comment]
Opps.. I made a wrong ref.

**Comment by cab105** [comment]
@ngtuna Did you already beat me to the punch?

**Comment by ngtuna** [comment]
@cab105 Haha just a reference mistake. Good to see you @cab105

**Comment by cab105** [comment]
Likewise.  BTW, @sebgoa PR is out to you.  Looks like the version is expected to be updated by hand.

**Comment by ngtuna** [comment]
Correct. Version is being updated by hand. Any idea we can have it updated automatically ?

**Comment by cab105** [comment]
Not from what I can tell.  We can take a known tag and derive its hash, but not the other way around, at least using git rev-parse.  At least given how the kompose build scripts are being used.  Even then, this technique still won't work if you use go build natively.

**Comment by surajssd** [comment]
https://github.com/skippbox/kompose/pull/180 is merged so this can be closed!

Result on current master:
```bash
$ kompose --version
kompose version dev (HEAD)
```

**Comment by dustymabe** [comment]
This is now a problem again after the last release. Any ideas for making this dynamic?
