### ISSUE TITLE
`--provider` flag for kompose

### ISSUE THREAD

**Issue by surajssd** [skippbox/kompose#179]
The way, "what artifacts to generate?" is not handled consistently.
Having a provider flag will enable the further implementation of pref file, so that the way artifacts generation is handled is unified.

`convert` ->  

```bash
validate: --provider and individual flags(--ds, --rs) cannot be together

if --provider given
    if provider is openshift
        generate dc, imagestreams, svc, routes, pvc(if needed)
    else if provider is foo
        generate x, y, z
    else
        default to k8s
        generate deployments, svc, pvc(if needed)

else if individual flags are given generate those artifacts
    deployments, svc, daemonsets, replicasets, rc can be generated for both providers
    but imagestreams, routes can be created for openshift only
    

else if --provider is not given and individual flags are not given
    if pref file given read artifacts from there
    else
        default to k8s
        generate deployments, svc, pvc(if needed)
```     
                

`up` ->

individual flags not supported

```bash
if --provider given
    if provider is openshift
        generate dc, imagestreams, svc, routes, pvc(if needed)
    else if provider is foo
        generate x, y, z
    else
        default to k8s
        generate deployments, svc, pvc(if needed)
else if --provider is not given
    if pref file given read artifacts from there
    else
        default to k8s
        generate deployments, svc, pvc(if needed)
```

Closing this unblocks #39

**Comment by surajssd** [comment]
@ngtuna @kadel do we need this flag?

**Comment by ngtuna** [comment]
@surajssd If we see the preference file is mandatory, then we can restrict provider declared in profile inside the file. Otherwise, somehow user wanna skip the file and go directly with `--provider` flag, but I will see there are might be other flags need to be declared along with. Of course support both cases makes kompose more flexible, but also reduce simplicity. I go with the first option. Let's wait for @kadel comment.

**Comment by surajssd** [comment]
@ngtuna we don't want to restrict user to have preference file, that's for sure.

Or we can use other approach as, create a pref file if its not there alongside docker-compose file, with default profile of k8s and artifacts/objects to generate will be `deployments` and `svc`.

**Comment by ngtuna** [comment]
Yes we can generate the file by default. And probably support a subcommand `kompose config` in order to keep user away from editing manually (probably lead to wrong configuration). Like `kubectl config`
