### ISSUE TITLE
go 1.5 not building

### ISSUE THREAD

**Issue by sebgoa** [skippbox/kompose#181]
just to confirm, we are now using go 1.6, and 1.5 does not work anymore.

travis runs 1.6

we need to update the readme

**Comment by kadel** [comment]
You should be able to compile Kompose with go 1.5

on go1.5 I can build with `cgo` disabled it like this:
```
CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -o kompose -tags experimental ./cli/main
```

I don't know why, but if I try to build it with `cgo` it fails on:
```
# github.com/skippbox/kompose/vendor/github.com/opencontainers/runc/libcontainer/system
cannot load DWARF output from $WORK/github.com/skippbox/kompose/vendor/github.com/opencontainers/runc/libcontainer/system/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0
```
With go1.7  I can build it in both cases (with and without `cgo`).
It looks like that for go1.5 `cgo` has to be disabled. I don't know why :-( Maybe I'm doing something wrong. I don't know much about go compiler :-(
Maybe  @janetkuo has idea?

**Comment by ngtuna** [comment]
So I made a direct update to README accordingly for both cases. https://github.com/skippbox/kompose/commit/9cb74ed0231aa31771394d355c936aa88a2f2ce8
