### ISSUE TITLE
come up with a release schedule

### ISSUE THREAD

**Issue by dustymabe** [skippbox/kompose#187]
It would be nice if we can come up with a release schedule so that we can get new features out to users and also give them some baseline to report issues against. Could we possibly come up with a release strategy (time based/feature based, etc) for the project?

**Comment by sebgoa** [comment]
yeah, linked to #70 

I will close it as dupe if you don't mind, but label #70 as P0

**Comment by dustymabe** [comment]
Sure - that works. Thanks!
