### ISSUE TITLE
script/godep-restore.sh doesn't seem to work correctly

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kompose#194]
I tried running `script/godep-restore.sh` in a fresh $GOPATH, and then removed Godeps and vendor folders and then running `godep save ./...` in order to save them again. The new born Godeps.json looks quite different with the current one we have in upstream.

**Comment by ngtuna** [comment]
However, building kompose with the new generated vendor/ run successfully. Many packages have been removed.

**Comment by kadel** [comment]
This is not godep fault but ours. 
We let `vendor` get out of sync. Every time we add or remove import we should run `save`.
We don't do that so we have few unused libs in vendor.

**Comment by ngtuna** [comment]
Right. So I am going to update vendor

**Comment by ngtuna** [comment]
closed via https://github.com/skippbox/kompose/pull/195
