### ISSUE TITLE
Support TLS with token endpoints

### ISSUE THREAD

**Issue by runseb** [skippbox/kompose#2]
We need to make sure we can target k8s api servers that are setup with TLS and token access.

**Comment by runseb** [comment]
easiest right now, is to run a proxy

    $ kubectl proxy --port=8080

and let kompose hit localhost:8080

**Comment by ngtuna** [comment]
Let me see

**Comment by runseb** [comment]
this is low priority, the proxy does the job,

**Comment by runseb** [comment]
this was fixed in the kompose-lite branch, by reading the local kubeconfig..
