### ISSUE TITLE
Creates json files with a .yaml ending

### ISSUE THREAD

**Issue by luebken** [skippbox/kompose#20]
When I convert a compose file I get .yaml files:
````
$ kompose k8s convert -d
$ ll | grep 'rc\|svc\|deploy'
-rw-r--r--   1 mdl  staff   786 23 Feb 12:57 currentweather-deployment.yaml
-rw-r--r--   1 mdl  staff   895 23 Feb 12:57 currentweather-rc.yaml
-rw-r--r--   1 mdl  staff   746 23 Feb 12:57 redis-deployment.yaml
-rw-r--r--   1 mdl  staff   747 23 Feb 12:57 redis-rc.yaml
-rw-r--r--   1 mdl  staff   292 23 Feb 12:57 redis-svc.yaml
```

But they contain json. e.g.
```
cat redis-svc.yaml
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "redis",
    "creationTimestamp": null,
    "labels": {
      "service": "redis"
    }
  },
  "spec": {
    "ports": null,
    "selector": {
      "service": "redis"
    }
  },
  "status": {
    "loadBalancer": {}
  }
}
```

Context: 
Grabbed the Mac latest version. Although it says:
````
$ kompose --version
kompose version 0.0.0-dev (825d5dc)
```

**Comment by runseb** [comment]
LOL, good catch.

The bottom line kompose submits the json to your k8s endpoint during the conversion, we just write the files for convenience. And if you use kubectl create it accepts both json or yaml.

The file extension does not really matter, but I will fix it.

thanks (can't believe I missed that).

**Comment by luebken** [comment]
l'm acutally looking for an rc,svc file generator. So for me the "convenience" is the actual feature. ;-)
But would prefer yml.

**Comment by runseb** [comment]
I will check, should be a straightforward fix

**Comment by runseb** [comment]
Ok it's fixed in master (writing .json extension instead of .yaml), I uploaded a new pre-release for it.
I will try to work on passing an option to write yaml instead, maybe @cab105 or @ngtuna will get to it before me.

**Comment by ngtuna** [comment]
Let me take this ticket.

**Comment by ngtuna** [comment]
You can now generate yaml files with -y option

**Comment by luebken** [comment]
:+1:
