### ISSUE TITLE
Provide a tar.gz download with a unified binary name in it

### ISSUE THREAD

**Issue by Mayeu** [skippbox/kompose#21]
Hello,

Instead of providing a direct link to the binary file, can you you provide tar.gz with the architecture in the archive name, but the binary in it simply named `kompose`. This is to simplify packaging, in the case of homebrew it really simplify the formula script when the file downloaded is an archive.

Thanks.

**Comment by runseb** [comment]
@Mayeu got it, I will work on this tonight

**Comment by Mayeu** [comment]
Thanks :+1:

**Comment by runseb** [comment]
@Mayeu can you try with the latest pre-release, it should be .tar.gz the way you need it

**Comment by runseb** [comment]
but we need to modify script/binary to provide tar.gz artifacts with a single kompose binary in it.

**Comment by Mayeu** [comment]
:+1: See skippbox/homebrew-tap#2
