### ISSUE TITLE
Support for Environment variables

### ISSUE THREAD

**Issue by t-ivanov** [skippbox/kompose#23]
I was not able to convert images containing the environment construct:
"environment:
    DATABASE_URI: $DATABASE_URI
    APP_ID: $APP_ID
..."
Removing them fixed the problem and the json files were generated.

**Comment by runseb** [comment]
Have you tried the pre-release version of kompose 0.0.3-alpha.2 ?

**Comment by t-ivanov** [comment]
Yes, I tried only the latest v0.0.3.alpha.2.

**Comment by runseb** [comment]
@t-ivanov could you put part of you compose file in a gist so that I can look at it and debug this ?

**Comment by t-ivanov** [comment]
Sure, here is the compose file I was playing with: https://github.com/yongjhih/docker-parse-server/blob/master/docker-compose.yml 
It worked after I removed the first and the last images with environment variables.

**Comment by runseb** [comment]
Ok, I can reproduce with a different compose file. It is the use of the $ variables in environment which causes the issue.

I will try to find a fix. Even though parametrized templates are not yet totally supported in Kubernetes.

**Comment by t-ivanov** [comment]
I see, variables with $ values are not so typical. Thanks for the assistance! :)

**Comment by runseb** [comment]
we also have an issue with the env variables separator, right now we only test for "=" , I will add ":"

thanks

**Comment by ngtuna** [comment]
Already added. Closed
