### ISSUE TITLE
Support privileged container

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kompose#24]
Sometimes need to run container in privileged mode.

Compose option: `privileged: true`
K8S option: `--allow_privileged=true`

**Comment by runseb** [comment]
it's more than this. The kubelet needs to allow privileged container but the yaml/json of a pod needs to have a key for security context which makes the pod privilege.

**Comment by ngtuna** [comment]
Fixed 3998b2ad0d86822350b741c1ae116a09d29ebbe4
