### ISSUE TITLE
Idea: kompose up, ps, delete, scale redirect to kubectl 

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#27]
`kompose up`, `ps`, `delete`, `scale` are duplicate of `kubectl`, but are easier to learn from compose users perspective. 

How about we suggest users the right kubectl command for each kompose command so that we don't need to reinvent the wheel? Something like:

```console
$ kompose up
To initiate your compose services, run "kubectl create -f web-rc.json -f web-svc.json".
```

Thoughts?

**Comment by dustymabe** [comment]
I like it but maybe we shouldn't make it so manual by making them copy/paste. Maybe something like:

```
$ kompose up
To initiate your compose services, run "kubectl create -f web-rc.json -f web-svc.json".
Would you like us to run that command for you now? (y/n) 
```

**Comment by ngtuna** [comment]
Ah ha, that makes more sense to me @dustymabe

**Comment by janetkuo** [comment]
@dustymabe Thanks that sounds good!

**Comment by runseb** [comment]
yes +1
we can support _up_, _ps_ and _delete_ via a simple wrapper to kubectl
and focus on the conversion for now.

**Comment by janetkuo** [comment]
Open question: what's the right behavior of `kompose up`? 

1. If there's no existing converted k8s files: it should tell the users to run `kompose convert`
2. If there's multiple existing k8s files: should it just create whatever config files we have? What if those files are stale (docker-compose.yaml updated since last conversion)? What if we have more than one k8s files (.yaml, .json, different controllers...)? We can just convert again and then create those k8s primitives, but we don't have the `options` in `kompose up` like we do in `kompose convert`.

**Comment by janetkuo** [comment]
> Open question: what's the right behavior of kompose up?

Update per earlier discussion with @runseb and @ngtuna: `kompose up` will do the equivalent of `kompose convert && kubectl create -f <svc_files> -f <deployment_files> ...`

**Comment by ngtuna** [comment]
link to https://github.com/skippbox/kompose/issues/40

**Comment by ngtuna** [comment]
Close as dup #40 #41

**Comment by janetkuo** [comment]
@ngtuna what about `kompose ps` and `kompose scale`?

**Comment by ngtuna** [comment]
@janetkuo By closing this issue, I just wanna make some clean up on issues. We can have another discussion on `kompose ps` and `kompose scale`, then we open the corresponding issues for them later.
