### ISSUE TITLE
Simplify kubernetes api server config

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#31]
To use `kompose`, one needs to either put api server address in `.kuberconfig` through `kompose kubeconfig --host` or have it defaulted to `localhost:8080` and run a proxy with `kubectl proxy --port-8080`. Could we simplify that?

For example, we could create the proxy inside `kompose`, or get server address from `kubectl config view`.

**Comment by janetkuo** [comment]
Or, we could do this
```go 
import cmdutil "k8s.io/kubernetes/pkg/kubectl/cmd/util"

f := cmdutil.NewFactory(nil)
client, err := f.ClientConfig()
```

to get a restclient.Config for accessing the server, instead of `restclient.Config{Host: server}` (which doesn't contain authentication info).

**Comment by runseb** [comment]
Yup, we will try to address this in the refactor. But feel free to send a PR.

thanks

**Comment by ngtuna** [comment]
Done. Now kompose will automatically get client config from kubectl. Removed `kubeconfig` subcommand.
