### ISSUE TITLE
kompose lite 

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#32]
I'm wondering if we can have a lighter `kompose` that contains only the necessary commands for transformation from docker compose format to Kubernetes API objects -- especially `convert` (`kompose k8s convert`).

**Comment by runseb** [comment]
Hi @janetkuo yes that's something that a few other people have asked for. We are going to work on it asap. cc/ @ngtuna @odacremolbap

**Comment by ngtuna** [comment]
@janetkuo I made this commit for the kompose-lite you mentioned above. Please have a try. https://github.com/skippbox/kompose/commit/50d6711be7ca74de01f01912b22bc05f85d99aaf

@runseb I think we can cut a new release with this.

**Comment by janetkuo** [comment]
@ngtuna thanks; it works great!!
