### ISSUE TITLE
Failed to build kompose: cannot find package "speter.net/go/exp/math/dec/inf" 

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#33]
See https://travis-ci.org/skippbox/kompose/builds/136012384

**Comment by ngtuna** [comment]
Hi @janetkuo it's already issued here https://github.com/skippbox/kompose/issues/30 That change came from k8s dependency. I am gonna add this package manually to vendor folder. For latest k8s package, it no longer happens but at this moment kompose's still based on k8s 1.2.

**Comment by janetkuo** [comment]
@ngtuna noted, thanks! Closing as dup
