### ISSUE TITLE
We don't have any tests

### ISSUE THREAD

**Issue by runseb** [skippbox/kompose#34]
We should add a few test fixtures and run tests on Travis/circleCI.

**Comment by surajssd** [comment]
I am working on creating functional tests right now, will work on the unit tests once, the code refactor and code moving thing that @kadel and @ngtuna are working on, is done.

So one question: What framework are we using to do the functional testing? Plain shell scripts or framework like [avocado](https://avocado-framework.github.io/) or anything else?

**Comment by surajssd** [comment]
Added functional tests: https://github.com/skippbox/kompose/pull/89

**Comment by ngtuna** [comment]
We also need to add unit tests.

**Comment by surajssd** [comment]
@ngtuna yes will work on them once your refactor is in! So we can keep this open.

**Comment by janetkuo** [comment]
I'm adding unit test for komposeConvert in #104

**Comment by ngtuna** [comment]
Thanks @janetkuo for adding some unit tests and we will keep adding more. This issue can be closed now.
