### ISSUE TITLE
Add OpenShift support

### ISSUE THREAD

**Issue by kadel** [skippbox/kompose#36]
We would like to contribute OpenShift support to kompose2.
In core OpenShift is basically Kubernetes with some additional objects like `BuildConfig`, `DeploymentConfig`, `ImageStream` or `Route`.
With `BuildConfig` OpenShift can even support docker-compose `build` directive.

I guess that this first design question would be how command line is going to look like.
What if we use provider (orchestration  tool) name  as command and actions as subcommands?
Examples how it would look like:
```
kompose kubernetes convert
kompose kubernetes up

kompose openshift convert
kompose openshift up
```
When we do it like this, than in future different providers could even have different actions.

**Comment by ngtuna** [comment]
@kadel  I suggest to go with:

```kompose convert --provider openshift```

Then we can support different providers with a small change of the current code base. Also IMHO adding `--provider` flag looks better

**Comment by janetkuo** [comment]
+1 on adding flag

**Comment by runseb** [comment]
I was thinking about this a bit, especially considering that I feel the options are getting a bit "crazy".

Maybe we should use subcommands to have a better structure and avoid so many boolean definition and if statements.

We could use subcommands for objects and keep the option for --stdout --out --yaml and --provider.

something like:

```
kompose convert daemonset
kompose convert daemonset --provider openshift
kompose convert rc
kompose convert rc --provider openshift
```

By default we create a service for every docker-compose service.

thoughts ?

**Comment by janetkuo** [comment]
I like your proposal. Will we still provide default controller (i.e. deployment) when `kompose convert` is executed without specifying which controller? I'm leaning toward yes, since users don't need to figure out which to choose if they're new to kubernetes.

**Comment by janetkuo** [comment]
@runseb does your proposal imply that converting compose to multiple types of controllers (e.g. `kompose convert -d -ds`) won't be supported anymore?

**Comment by kadel** [comment]
I'm afraid that this might get little messy :cry: 

As OpenShift adds few thinks on top of Kubernetes you will get options that are not valid for all providers.
For example:
`kompose convert deploymentconfig` -  This will be valid only for OpenShift and not for Kubernetes.

**Comment by ngtuna** [comment]
I also like Sebastien's approach. Currently convert functiin doesn't look good because of many boolean variables and if statements. Need to think a bit more in order to cover multiple controllers generation.

We can add validation for subcommand relating to Openshift primitives only.

**Comment by kadel** [comment]
> I also like Sebastien's approach. Currently convert functiin doesn't look good because of many boolean variables and if statements. Need to think a bit more in order to cover multiple controllers generation.
> 
> We can add validation for subcommand relating to Openshift primitives only.

For me it seems little strange because it emphasize choosing controller object to much.
I think of choosing controller object as optional configuration how convert should behave.
With syntax like this I would expect that controller is required. But that shouldn't be the case.

I expect that most user will use default one and won't care that much about others.

**Comment by runseb** [comment]
I suggest to @kadel assigns this issues to himself and starts working in a branch.

For the configuration, we need to investigate #39 , using a `.kompose` preference file, which can have multiple profiles.

The idea being that using kubernetes or openshift or any other future provider could be hidden and made default. That way users familiar with docker-compose can use `kompose up` at the beginning without worrying about providers or default objects.

**Comment by kadel** [comment]
+1 for preference file, this will keep command-line clean and simple.

I will keep in my mind that we might go this way when working on openshift provider.

**Comment by ngtuna** [comment]
Can we close this one? @kadel @surajssd

**Comment by kadel** [comment]
I think we can close this. Basic OpenShift support has been merged. We can always open new issues to track adding additional features.
