### ISSUE TITLE
kompose / kompose-lite should print warning messages for unsupported fields 

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#36]
so that users know which fields are ignored

Perhaps warnings like what docker-compose produces when creating DABs
https://github.com/docker/docker/blob/master/experimental/docker-stacks-and-bundles.md#producing-a-bundle
```console 
$ docker-compose bundle
WARNING: Unsupported key 'network_mode' in services.nsqd - ignoring
WARNING: Unsupported key 'links' in services.nsqd - ignoring
WARNING: Unsupported key 'volumes' in services.nsqd - ignoring
```

**Comment by ngtuna** [comment]
Noted! Thanks @janetkuo

**Comment by ngtuna** [comment]
https://github.com/skippbox/kompose2/issues/3

**Comment by ngtuna** [comment]
Solved by [kompose2](https://github.com/skippbox/kompose2)
