### ISSUE TITLE
Refactor to provide CLI without fork

### ISSUE THREAD

**Issue by runseb** [skippbox/kompose#38]
We need to refactor this to extract the CLI alone.

That was a mistake to fork instead of simply importing the library to build the CLI.

We might need to create a separate project _kompose2_ and put the new CLI in there.

**Comment by ngtuna** [comment]
I'm doing that on a new orphan branch (kompose-2). Does it make more sense than creating a separate project ?

**Comment by ngtuna** [comment]
Now we have *kompose2* going. Closed issue.
