### ISSUE TITLE
Support docker bundles format as input

### ISSUE THREAD

**Issue by runseb** [skippbox/kompose#4]

**Comment by ngtuna** [comment]
https://github.com/docker/docker/pull/23522

**Comment by ngtuna** [comment]
There is an issue with package `github.com/docker/docker/api/client/bundlefile`: at this moment it is marked `// +build experimental`. That means go can't see it as a normal lib thus the building is fail.

```
$ go build -o kompose2 ./cli/main  
cli/app/app.go:30:2: no buildable Go source files in ...github.com/docker/docker/api/client/bundlefile
```

**Comment by runseb** [comment]
I think this library allows you to generate bundles from compose file. We might add that.

But what we want is to be able to take a bundle and transform it into k8s primitives. It might be tricky because the image reference in a bundle is the sha of the layer...and not the image tag (which is not immutable).

**Comment by ngtuna** [comment]
No Sebastien, that lib supports us to take a dab file and parse to `Bundlefile` struct. Then we are able to map to k8s objects.

Yes you're right. Image reference would be a tricky point.

**Comment by runseb** [comment]
ok good to know.

as a first pass, we might just extract an image name from docker hub and use the latest tag. Since k8s does not support referencing specific layers in the image field.

**Comment by ngtuna** [comment]
Working on `dab-support` branch

**Comment by ngtuna** [comment]
@runseb Figure out the current revision of `libcompose` is too old in order to support mapping `bundles` fields to `compose` fields then to k8s primitives... This's such a pain if we keep enforcing it. I'm going to level up `libcompose` revision. It should be good as we can solve #11 in the meantime.

**Comment by runseb** [comment]
you mean update the godeps hash for lib compose ?
will this break the current code ?

**Comment by ngtuna** [comment]
Correct. No it doesn't harm the current code much. But I keep master branch stable and mainly work in separate dab-support branch. Then we can decide to merge when it done.

**Comment by ngtuna** [comment]
Closed by https://github.com/skippbox/kompose/commit/91d981858f595243a7ea2b699d0fd064a6dff682
