### ISSUE TITLE
new behavior of `kompose delete`

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kompose#41]
Adding flag `-a/--all` in order to delete all resources.
Consider to rename to `kompose rm`

**Comment by janetkuo** [comment]
`docker-compose rm` is used for removing "stopped" service containers, whereas `kubectl delete` can (and often) be used to remove the running ones.

**Comment by ngtuna** [comment]
Thanks @janetkuo for pointing it out. I am not thinking about `kompose delete` much right now. Paying more attention on `kompose up`. However, let's say we can have `kompose rm` to firstly stop containers running on k8s and then remove them. Don't want to be duplicated with `kubectl delete` but somehow we can add `kompose stop` to only do stop action. However, we should be very careful to not going into the same way last time when we overlapped `kubectl` functions. Interactive mode still be good option to go.

**Comment by ngtuna** [comment]
So, after some investigating, I see we need a thing is in contrast with `kompose up`. So I suggest:

```console
- `kompose down --file/--bundle <input_file>` : delete deployment and svc
- `kompose down --all`: delete all resources (deployment, rc, svc, ds)
```

Anything else ?
/cc @janetkuo @runseb

**Comment by janetkuo** [comment]
Is `kompose down --all` going to delete all resources in the system, regardless if it's created by kompose or not? Not sure if it's expected behavior from the users' perspective -- depends on their work flow

**Comment by ngtuna** [comment]
Yes it's a critical action. We can ask for confirmation like this:

```console
$ kompose down --all
This action is going to delete all resources in all namespaces (except kube-system) in the kubernetes cluster. 
Are you sure to continue ? (y/n)
```

**Comment by runseb** [comment]
I don't think `kompose down` should delete everything. It should only delete the resources that the conversion created.

```
kompose down -f docker-voting.yml
```

should delete the deployments and services that it creates.

At least that's what I would expect.

**Comment by ngtuna** [comment]
So I will go merging `kompose down` without supporting `--all` flag. We can make a follow-up PR for this later.

**Comment by ngtuna** [comment]
Close via https://github.com/skippbox/kompose/pull/113
