### ISSUE TITLE
[Discuss] Optimize convert function

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kompose#44]
In order to support different types of input format (dab, compose v1, compose v2, etc) and break down the convert function as well, I am thinking about creating a generic struct like this:

```
type komposeSet struct {
  Image string
  Name  string
  Volume  []Volumes
  Network []Networks
  Environment []string
  Port  []Ports
  Command string
}
```

I will think more on mandatory fields need to be declared of this struct.

Idea behind is that we take file from different input, build corresponding `parsing` function to map it to `komposeSet` struct. Then the main convert function will only do the transformation from `komposeSet` to k8s controllers and service. With that strategy, we also can cut-off the dependency on libcompose's structs between versions.

Thought ?

**Comment by runseb** [comment]
+1 . except the name. Maybe komposeMap or komposeObject

**Comment by kadel** [comment]
+1 I really like idea of intermediate format.

The struct would need to be little bit bigger to catch more things like cpu, memory limits and builds.

Maybe we could base this on libcompose [ServiceConfig](https://godoc.org/github.com/docker/libcompose/config#ServiceConfig). Not that we would use this directly, but only base our struct on this. I think that this captures most of the options that container can have.

**Comment by ngtuna** [comment]
@kadel Agreed. I'm building this struct. Try to get as many common fields as possible.

**Comment by janetkuo** [comment]
+1 on adding this struct, and +1 on naming it `komposeObject`
