### ISSUE TITLE
Write an architecture document for kompose

### ISSUE THREAD

**Issue by pradeepto** [skippbox/kompose#45]
Kompose is getting a lot of traction. Would be a nice thing to have an architecture document that will help document kompose internals and also help new contributors to get ramped up.

**Comment by ngtuna** [comment]
link to #55

**Comment by kadel** [comment]
So I tried to put something together. here is first draft: https://docs.google.com/document/d/1p3QUpMlCOHfncfemcja3ArNb9-aLbTc0foHYJ5QdCgM/edit?usp=sharing

**Comment by ngtuna** [comment]
Close by https://github.com/skippbox/kompose/commit/45c482977822e82453f49f2a3ec1d729cde55776
