### ISSUE TITLE
Unable to go build 

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#49]
```console
$ go build -o kompose ./cli/main/
cli/app/app.go:29:2: no buildable Go source files in go/src/github.com/skippbox/kompose/vendor/github.com/docker/docker/api/client/bundlefile
```

This is because of a recent change to vendor/github.com/docker/docker/api/client/bundlefile/bundlefile.go:
```go
// +build experimental

package bundlefile
```

Build error went away after removing `// +build experimental`. 

cc @kadel

**Comment by ngtuna** [comment]
@janetkuo correct. I also have to remove // +build experimental when doing build locally. However @kadel submitted a patch to support building with experimental packages with gox. So it's no problem at all.

**Comment by ngtuna** [comment]
@surajssd can you try `gox -osarch="linux/amd64" ./cli/main/` ?

**Comment by kadel** [comment]
@janetkuo If you add experimental build tag you can build it without modifying boundlefile.go like this: 
```
go build -tags experimental -o kompose ./cli/main/
```

**Comment by ngtuna** [comment]
Closed by https://github.com/skippbox/kompose/commit/fa0930de062bf6951af0010dae6c0394311ba3fa
