### ISSUE TITLE
Consider changing `--rc` flag to bool and adding `--replicas`

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#52]
Right now all flags for specifying controller types are `bool`, except for `--rc`, which is `int`. 

This is confusing because I cannot do this 
```console
$ ../kompose convert --rc -y
Incorrect Usage.
```

And this (surprisingly) gives me a deployment 
```console
$ ../kompose convert --rc="0" -y
file "redis-svc.yaml" created
file "web-svc.yaml" created
file "redis-deployment.yaml" created
file "web-deployment.yaml" created
```

I propose that we change `--rc` back to `bool` and add another `int` flag for specifying replicas, since other controllers also take `replicas` in their spec. We can default it to `-1` as unset, and then we don't specify it in spec (and let K8s API server decide the default value). If it's set to something >= 0, we set it explicitly.

**Comment by ngtuna** [comment]
+1. Are u going to do or shoud I take it?

**Comment by janetkuo** [comment]
I can take this one
