### ISSUE TITLE
Consider changing `--from-bundles` (bool) to `--bundle-file` (string)

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#53]
How about we make the flag for specifying bundles to something similar to `--file` (e.g. `--bundle-file`)? It'll be easier to specify than `--from-bundles` + `--file=xxx`. We can validate the flags so that either `--file` or `--bundle-file` can be specified at a time.

**Comment by ngtuna** [comment]
+1. when adding --from-bundles flag I was just thinking about reusing --file flag. Could you make a commit for this?

**Comment by janetkuo** [comment]
Sure

**Comment by runseb** [comment]
so +1 I confirm, this is not very intuitive:

```
$ ./kompose convert --from-bundles ./docker-compose-bundle.dsb 
FATA[0000] Failed to parse bundles file: %!(EXTRA *errors.errorString=JSON syntax error at byte 1: invalid character 'm' looking for beginning of value) 
$ ./kompose convert --from-bundles --file docker-compose-bundle.dsb 
file "web-svc.json" created
file "redis-svc.json" created
file "web-deployment.json" created
file "redis-deployment.json" created
```

**Comment by ngtuna** [comment]
@janetkuo: after you finish the patch to introduce `--bundle-file` flag, I will update README for both bundlefile and compose v2 guidances

https://github.com/skippbox/kompose/issues/54
