### ISSUE TITLE
update README for bundles, compose v2

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kompose#54]

**Comment by kadel** [comment]
Just reminder that we should also update Building section in README and add note about  requiring running `go build` with `-tags experimental` because we depended on dab support, that is still experimental feature in docker.

**Comment by ngtuna** [comment]
@kadel Here you are https://github.com/skippbox/kompose/commit/fa0930de062bf6951af0010dae6c0394311ba3fa

**Comment by ngtuna** [comment]
Closed by https://github.com/skippbox/kompose/commit/0e891f5b328b850db1f241d1bf9037a51b77226e
