### ISSUE TITLE
Breaking code in app.go to multiple packags

### ISSUE THREAD

**Issue by kadel** [skippbox/kompose#55]
What if we would break `app.go` to multiple packages?

I suggest creating notion of loaders and transformers.
Loader would load input file and convert it to komposeObject.
Transformer would convert komposeObject to target format.
Every loader and every transformer would live in its own package.
```
pkg/loader/dockercompose/
pkg/loader/boundlefile/

pkg/transformer/kubernetes/
pkg/transformer/openshift/
```

It could look like this:

```
                  +------+          +-----------+
input file -----> |loader|          |transformer| -----> output files
                  +------+          +-----------+
                     |                    ^
                     |                    |
                     |                    |
                     +--> komposeObject --+
```

**Comment by ngtuna** [comment]
Big +1 @kadel . It makes our code looks brighter and motivate new comers who would like to step forward. I will create `docs` folder then we can put all thoughts into. I can give a hand to implement this design if you'd prefer.

**Comment by ngtuna** [comment]
@kadel are you working on it? I can take this one if you'd prefer to keep working on OpenShift support #36  and preference file #39 .

**Comment by kadel** [comment]
I haven't stared on this yet. But I think we should do this before #39 and #36  because breaking app.go will probably involve a lot of code moving.

We can try together design some interfaces around `komposeObject` than it should be easy to break code and one of us can do loaders and other transformers.
