### ISSUE TITLE
Should we support converting to Replica Sets?

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#63]
Since we discourage people from using Replica Sets directly (instead they should use Deployments), how about removing the support for converting to RS? On the other hand, converting to Replication Controllers makes sense for people haven't adopted Deployments.

**Comment by kadel** [comment]
I was also thinking about this and I agree completely, we should discourage people from using Replica Sets directly.

**Comment by surajssd** [comment]
Or can we have it on k8s's version ? Like for k8s 1.2 we support `Deployments` by default and for before we use replication controllers. Or introduce some kinda flag?

**Comment by pradeepto** [comment]
@surajssd That will add unnecessary complications to the code base. Since kompose is new upcoming tool, I wonder if it makes sense to support features that are being actively discouraged/deprecated.

:+1:  @janetkuo with this suggestion.

**Comment by ngtuna** [comment]
+1 @janetkuo
