### ISSUE TITLE
Bug: incorrect version 

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#64]
Downloaded release file from https://github.com/skippbox/kompose/releases/tag/v0.0.1-beta.1
```console
$ kompose --version 
kompose version 0.0.1-alpha (HEAD)
```

It should instead give me:
```console
$ kompose --version 
kompose version 0.0.1-beta (fa0930d)
```

Related code https://github.com/skippbox/kompose/blob/master/version/version.go

**Comment by janetkuo** [comment]
Also in the release note we can provide checksums and installation guide, something like this:

## Installation
### Linux 
```
curl -Lo kompose https://github.com/skippbox/kompose/releases/download/v0.0.1-beta.1/kompose_linux-amd64 && chmod +x kompose && sudo mv kompose /usr/local/bin/
```

## Checksums 
### Linux 
```
$ openssl sha1 /usr/local/bin/kompose
SHA1(/usr/local/bin/kompose)= 826c247a4bdca44d2b68bef48d6649dd86813ef2
```

**Comment by ngtuna** [comment]
closed by https://github.com/skippbox/kompose/commit/bc7705157ade6dbf2e8d5c7b142257e0b38ec223

**Comment by janetkuo** [comment]
The latest release gives me 
```
$ kompose --version 
kompose version 0.0.1-beta (HEAD)
```

Shouldn't HEAD be replaced with commit number (in this case, https://github.com/skippbox/kompose/commit/c4d62c99eeeccbaaa7dbf838e79dcaf4e346c4b8)?

**Comment by ngtuna** [comment]
Which release are u trying ? @janetkuo From my side:

```console
$ wget https://github.com/skippbox/kompose/releases/download/v0.0.1-beta.2/kompose_linux-amd64.tar.gz
$ tar zxvf kompose_linux-amd64.tar.gz
$ kompose_linux-amd64/kompose --version
kompose version 0.0.1-beta (HEAD)
```

**Comment by janetkuo** [comment]
Yes it's correct, but `HEAD` should be a commit number, right?

**Comment by ngtuna** [comment]
Ah.. I missed it. You're totally right. I made a straight-forward commit to master https://github.com/skippbox/kompose/commit/1b501619b7826892155625b30a8548117d883ce3
