### ISSUE TITLE
Print warning for unsupported fields in docker-compose format  

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#71]
Follow up #3

We're now printing warnings of unsupported fields in their names defined in [libcompose](https://github.com/docker/libcompose/blob/release/0.2.0/config/types.go#L68), but not their names in [docker-compose file format](https://docs.docker.com/compose/compose-file/).  

For example, this 

```console
$ cat nginx.yml
nginx:
  image: nginx
  dockerfile: foobar
  build: ./foobar
  cap_add:
    - ALL
  container_name: foobar

$ kompose convert -f nginx.yml
WARNING: Unsupported key Build - ignoring
WARNING: Unsupported key CapAdd - ignoring
WARNING: Unsupported key ContainerName - ignoring
WARNING: Unsupported key Dockerfile - ignoring
```

should give me the following warnings instead:

```console
$ kompose convert -f nginx.yml
WARNING: Unsupported key build - ignoring
WARNING: Unsupported key cap_add - ignoring
WARNING: Unsupported key container_name - ignoring
WARNING: Unsupported key dockerfile - ignoring
```

**Comment by surajssd** [comment]
@janetkuo and @ngtuna why can we use `logrus.Warningf` instead of `fmt.Println` at https://github.com/skippbox/kompose/blob/master/cli/app/app.go#L1076 ?

**Comment by surajssd** [comment]
Also when doing `--stdout` the warnings should be either printed in  a way so that user can still pipe the output to a `kubectl`

**Comment by surajssd** [comment]
Using following docker-compose file
```yaml
$ cat docker-compose.yml 
version: "2"

services:
  mariadb:
    image: centos/mariadb
    container_name: mariadb
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: etherpad
      MYSQL_DATABASE: etherpad
      MYSQL_PASSWORD: etherpad
      MYSQL_USER: etherpad
```

When directly piped fails
```bash
$ kompose convert  --stdout | kubectl --namespace=kompose create -f -
yaml: line 2: could not find expected ':'
```
Because the output starts with 

```json
$ kompose convert  --stdout
WARNING: Unsupported key Networks - ignoring
{
  "kind": "Service",
  "apiVersion": "v1",
[SNIP]
```

**Comment by ngtuna** [comment]
Good catch @janetkuo and @surajssd . Thanks. I will update shortly

**Comment by janetkuo** [comment]
Closing as this is now fixed by https://github.com/skippbox/kompose/commit/55ae6e75383a3024e6ad5196d8d1280be9c7e39f

**Comment by janetkuo** [comment]
Right now there are unsupported keys / fields not covered by warnings, such as [volume configs](https://docs.docker.com/compose/compose-file/#/volume-configuration-reference).

**Comment by surajssd** [comment]
@ngtuna yes its good that we have we now don't print the output to `stdout` so I can pipe output right now! :+1:

**Comment by ngtuna** [comment]
@janetkuo Agree. We haven't covered both [volume configs](https://docs.docker.com/compose/compose-file/#/volume-configuration-reference) and [network configs](https://docs.docker.com/compose/compose-file/#/network-configuration-reference).

**Comment by ngtuna** [comment]
Closed by https://github.com/skippbox/kompose/commit/14cf356a08374bc069477aa47a46b340abb782b4
