### ISSUE TITLE
Add warnings/error for image not specified 

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#80]
Follow-up https://github.com/skippbox/kompose/pull/79#issuecomment-237332663:

`image` is a required field in Kubernetes and without it the generated file can't be used. 

From [compose spec](https://docs.docker.com/compose/compose-file), v1 doesn't allow `image` being specified with `build`, and v2 allows you to do that but the `image` will be built from `build`. 

We can print an error when we see `build` in the compose file. Would love to hear more thoughts.

**Comment by surajssd** [comment]
With Kubernetes:
- `image` is must, until we come up with a build story

With OpenShift:
- If `build` given we can create `buildconfig`
- if `image` given well and good

cc: @kadel

**Comment by ngtuna** [comment]
Currently there is an unsupported key message if we see `build` in the compose file.
@surajssd : while working on the issue https://github.com/skippbox/kompose/issues/92 of having `image` and `build` in the same compose service, you can also add a check for required fields like `image`

**Comment by ngtuna** [comment]
Closed via https://github.com/skippbox/kompose/pull/195
