### ISSUE TITLE
Update libcompose to v0.3.0

### ISSUE THREAD

**Issue by kadel** [skippbox/kompose#95]
There is new release of libcompose with support for v2 compose.
We should update our dependencies to use this release.

**Comment by surajssd** [comment]
please do libcompose head once https://github.com/docker/libcompose/pull/358 gets in!

**Comment by ngtuna** [comment]
:ok_hand:

**Comment by kadel** [comment]
I have created PR #112 that updates to libcompose v0.3.0.
After fix for #92 is merged to libcompose we can do another separate update

**Comment by surajssd** [comment]
@kadel sure not a problem :+1:
